#pragma once

#define PROGRAMMER_VERSION_MAJOR 1
#define PROGRAMMER_VERSION_MINOR 0
#define PROGRAMMER_ROM_SIZE      (256UL*1024UL)
#define PROGRAMMER_MAX_LEN       128
#define PROGRAMMER_SECTOR_SIZE   4096UL
